DEFAULT_RAMP = {
    "TIME_LIMIT_IN_SECONDS": 60,
    "SPAWN_RATE": 1,
    "RAMP_EVERY_X_SECONDS": 60,
    "INITIAL_USERS": 1,
    "MAX_USERS": 10
}
DEFAULT_KPIS = {
    "REQUESTS_PER_SECOND": 0.5,
    "FAIL_RATIO_ALLOWED": 0.01,
    "RESPONSE_TIME_PERCENTILE_90_MILLISECONDS": 400,
    "RESPONSE_TIME_PERCENTILE_95_MILLISECONDS": 800,
    "RESPONSE_TIME_PERCENTILE_99_MILLISECONDS": 1200
}