version: '3'

services:
  master:
    build: .
    ports:
     - "8089:8089"
    volumes:
      - ./:${pwd}/mnt/locust
    command: "-f ${pwd}/mnt/locust/${LOCUST_LOCUSTFILE} --master --host=${HOST} --headless --html=report.html"
  
  worker:
    build: .
    volumes:
      - ./:${pwd}/mnt/locust
    command: -f ${pwd}/mnt/locust/${LOCUST_LOCUSTFILE} --worker --master-host master --host=${HOST}