PREVIOUS_LAUNCHES_INFO_RAMP = {
    "TIME_LIMIT_IN_SECONDS": 60,
    "SPAWN_RATE": 1,
    "RAMP_EVERY_X_SECONDS": 60,
    "INITIAL_USERS": 1,
    "MAX_USERS": 10
}
PREVIOUS_LAUNCHES_INFO_KPIS = {
    "REQUESTS_PER_SECOND": 0.1,
    "FAIL_RATIO_ALLOWED": 0.01,
    "RESPONSE_TIME_PERCENTILE_90_MILLISECONDS": 3000,
    "RESPONSE_TIME_PERCENTILE_95_MILLISECONDS": 4000,
    "RESPONSE_TIME_PERCENTILE_99_MILLISECONDS": 5000
}