# This is a basic workflow to help you get started with Actions

name: Locust Performance Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      workers:
        description: 'Number of worker nodes to be used in performance tests'     
        required: true
      locustfile:
        description: 'Define the locust performance test file name to be executed'     
        required: true
        default: 'dragons_info_load_test.py'     

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  performance-tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    #env variables
    env:
      LOCUST_LOCUSTFILE: dragons_info_load_test.py
      WORKERS: ${{ github.event.inputs.workers || 4 }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: AutoModality/action-clean@v1
        if: ${{ always() }} # To ensure this step runs even when earlier steps fail
      - uses: actions/checkout@v2

      - name: Start performance tests
        run: docker-compose up --scale worker=${WORKERS} --force-recreate --exit-code-from=master
      - name: export test report
        if: always()
        run: docker cp baselineperformancetest-locust_master_1:./home/locust/report.html .
      - name: export artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: locust-report
          path: report.html

